api:
  host: "0.0.0.0"
  port: 8000

test_data:
  path: "config/test_data.json"

llama_cpp:
  llama_bin_path: "/src/app/ai_service/llama_bin/llama-cli.exe"
  model_path: "/src/app/ai_service/models/mistral-7b-v0.1.Q4_K_M.gguf"
