name: Auto-Map Code, Tests & Jira

on:
  push:
    branches:
      - main

jobs:
  update_mapping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Analyze GIT Code Change Script
        run: python code/src/app/service/mapTestToCodeToJira/detectGitCodeChanges.py

      - name: Update BDDFeatureSet DB
        run: python code/src/app/service/mapTestToCodeToJira/updateBDDTestSet.py
